services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_DB: gup
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: gup
      DB_USERNAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    command: >
      sh -c "composer install &&
             php artisan migrate &&
             php artisan db:seed
             php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: >
      sh -c "npm install &&
             npm run dev -- --host"
    depends_on:
      - backend

volumes:
  gup_db: